# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='token.proto',
  package='tokens',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btoken.proto\x12\x06tokens\"6\n\x0b\x63\x65rtRequest\x12\x13\n\x0b\x63\x65rtificate\x18\x01 \x01(\t\x12\x12\n\nprivatekey\x18\x02 \x01(\t\"3\n\x0cloginRequest\x12\x11\n\tldap_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"N\n\x12lookuptokenRequest\x12\x11\n\tldap_name\x18\x01 \x01(\t\x12\x16\n\x0etoken_accessor\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"h\n\x12\x63reatetokenRequest\x12\x11\n\tldap_name\x18\x01 \x01(\t\x12\x0e\n\x06header\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x0b\n\x03ttl\x18\x04 \x01(\t\x12\x11\n\trenewable\x18\x05 \x01(\t\"B\n\x11renewtokenRequest\x12\x11\n\tldap_name\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0b\n\x03ttl\x18\x03 \x01(\t\"\x1e\n\x08Response\x12\x12\n\njsonstring\x18\x01 \x01(\t\"N\n\x12revoketokenRequest\x12\x11\n\tldap_name\x18\x01 \x01(\t\x12\x16\n\x0etoken_accessor\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"$\n\x0erevokeResponse\x12\x12\n\njsonstring\x18\x01 \x01(\t2\xf5\x02\n\x06Tokens\x12\x35\n\tldapLogin\x12\x14.tokens.loginRequest\x1a\x10.tokens.Response\"\x00\x12\x34\n\tcertLogin\x12\x13.tokens.certRequest\x1a\x10.tokens.Response\"\x00\x12=\n\x0blookupToken\x12\x1a.tokens.lookuptokenRequest\x1a\x10.tokens.Response\"\x00\x12=\n\x0b\x63reateToken\x12\x1a.tokens.createtokenRequest\x1a\x10.tokens.Response\"\x00\x12;\n\nrenewToken\x12\x19.tokens.renewtokenRequest\x1a\x10.tokens.Response\"\x00\x12\x43\n\x0brevokeToken\x12\x1a.tokens.revoketokenRequest\x1a\x16.tokens.revokeResponse\"\x00\x62\x06proto3'
)




_CERTREQUEST = _descriptor.Descriptor(
  name='certRequest',
  full_name='tokens.certRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='certificate', full_name='tokens.certRequest.certificate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='privatekey', full_name='tokens.certRequest.privatekey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=77,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='loginRequest',
  full_name='tokens.loginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ldap_name', full_name='tokens.loginRequest.ldap_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='tokens.loginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=130,
)


_LOOKUPTOKENREQUEST = _descriptor.Descriptor(
  name='lookuptokenRequest',
  full_name='tokens.lookuptokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ldap_name', full_name='tokens.lookuptokenRequest.ldap_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token_accessor', full_name='tokens.lookuptokenRequest.token_accessor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='tokens.lookuptokenRequest.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=210,
)


_CREATETOKENREQUEST = _descriptor.Descriptor(
  name='createtokenRequest',
  full_name='tokens.createtokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ldap_name', full_name='tokens.createtokenRequest.ldap_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='header', full_name='tokens.createtokenRequest.header', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='tokens.createtokenRequest.payload', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='tokens.createtokenRequest.ttl', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='renewable', full_name='tokens.createtokenRequest.renewable', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=316,
)


_RENEWTOKENREQUEST = _descriptor.Descriptor(
  name='renewtokenRequest',
  full_name='tokens.renewtokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ldap_name', full_name='tokens.renewtokenRequest.ldap_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='tokens.renewtokenRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='tokens.renewtokenRequest.ttl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=384,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='tokens.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonstring', full_name='tokens.Response.jsonstring', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=416,
)


_REVOKETOKENREQUEST = _descriptor.Descriptor(
  name='revoketokenRequest',
  full_name='tokens.revoketokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ldap_name', full_name='tokens.revoketokenRequest.ldap_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token_accessor', full_name='tokens.revoketokenRequest.token_accessor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='tokens.revoketokenRequest.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=496,
)


_REVOKERESPONSE = _descriptor.Descriptor(
  name='revokeResponse',
  full_name='tokens.revokeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonstring', full_name='tokens.revokeResponse.jsonstring', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=534,
)

DESCRIPTOR.message_types_by_name['certRequest'] = _CERTREQUEST
DESCRIPTOR.message_types_by_name['loginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['lookuptokenRequest'] = _LOOKUPTOKENREQUEST
DESCRIPTOR.message_types_by_name['createtokenRequest'] = _CREATETOKENREQUEST
DESCRIPTOR.message_types_by_name['renewtokenRequest'] = _RENEWTOKENREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['revoketokenRequest'] = _REVOKETOKENREQUEST
DESCRIPTOR.message_types_by_name['revokeResponse'] = _REVOKERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

certRequest = _reflection.GeneratedProtocolMessageType('certRequest', (_message.Message,), {
  'DESCRIPTOR' : _CERTREQUEST,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:tokens.certRequest)
  })
_sym_db.RegisterMessage(certRequest)

loginRequest = _reflection.GeneratedProtocolMessageType('loginRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:tokens.loginRequest)
  })
_sym_db.RegisterMessage(loginRequest)

lookuptokenRequest = _reflection.GeneratedProtocolMessageType('lookuptokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOOKUPTOKENREQUEST,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:tokens.lookuptokenRequest)
  })
_sym_db.RegisterMessage(lookuptokenRequest)

createtokenRequest = _reflection.GeneratedProtocolMessageType('createtokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETOKENREQUEST,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:tokens.createtokenRequest)
  })
_sym_db.RegisterMessage(createtokenRequest)

renewtokenRequest = _reflection.GeneratedProtocolMessageType('renewtokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENEWTOKENREQUEST,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:tokens.renewtokenRequest)
  })
_sym_db.RegisterMessage(renewtokenRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:tokens.Response)
  })
_sym_db.RegisterMessage(Response)

revoketokenRequest = _reflection.GeneratedProtocolMessageType('revoketokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVOKETOKENREQUEST,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:tokens.revoketokenRequest)
  })
_sym_db.RegisterMessage(revoketokenRequest)

revokeResponse = _reflection.GeneratedProtocolMessageType('revokeResponse', (_message.Message,), {
  'DESCRIPTOR' : _REVOKERESPONSE,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:tokens.revokeResponse)
  })
_sym_db.RegisterMessage(revokeResponse)



_TOKENS = _descriptor.ServiceDescriptor(
  name='Tokens',
  full_name='tokens.Tokens',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=537,
  serialized_end=910,
  methods=[
  _descriptor.MethodDescriptor(
    name='ldapLogin',
    full_name='tokens.Tokens.ldapLogin',
    index=0,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='certLogin',
    full_name='tokens.Tokens.certLogin',
    index=1,
    containing_service=None,
    input_type=_CERTREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='lookupToken',
    full_name='tokens.Tokens.lookupToken',
    index=2,
    containing_service=None,
    input_type=_LOOKUPTOKENREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='createToken',
    full_name='tokens.Tokens.createToken',
    index=3,
    containing_service=None,
    input_type=_CREATETOKENREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='renewToken',
    full_name='tokens.Tokens.renewToken',
    index=4,
    containing_service=None,
    input_type=_RENEWTOKENREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='revokeToken',
    full_name='tokens.Tokens.revokeToken',
    index=5,
    containing_service=None,
    input_type=_REVOKETOKENREQUEST,
    output_type=_REVOKERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOKENS)

DESCRIPTOR.services_by_name['Tokens'] = _TOKENS

# @@protoc_insertion_point(module_scope)
